name: g4_ex
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_gemma: ^0.15.3
  flutter_html: ^3.0.0-beta.2
  google_fonts: ^6.2.1
  http: ^1.6.0
  image_picker: ^1.1.2
  isar_community: ^3.1.0+2
  isar_community_flutter_libs: ^3.1.0+2
  path_provider: ^2.1.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  analyzer: 10.0.1
  isar_community_generator: ^3.1.0+2
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/protocols.json
